block-list-secret-scan: []
branch: master
directory:
- .
download-external-modules: false
evaluate-variables: true
framework:
- terraform
- github_actions
- cloudformation
mask: []
output:
- sarif
quiet: true
secrets-history-timeout: 12h
secrets-scan-file-type: []
summary-position: top
skip-check:
- CKV_TF_1
- CKV2_GHA_1
