# Generated by Django 4.1.4 on 2022-12-25 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coin',
            new_name='Task',
        ),
    ]
