# Generated by Django 4.1.4 on 2022-12-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0002_rename_coin_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
