# Generated by Django 4.1.4 on 2022-12-27 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0003_alter_task_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_id',
            new_name='celery_task_id',
        ),
    ]
