# Generated by Django 4.1.4 on 2022-12-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0004_rename_task_id_task_celery_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'created'), (2, 'running'), (3, 'done')], default=1),
        ),
    ]
