# Generated by Django 4.1.4 on 2022-12-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0005_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'created'), (2, 'running'), (3, 'done'), (4, 'revoked')], default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='hosts',
            field=models.ManyToManyField(to='ping.host'),
        ),
    ]
