# Generated by Django 4.1.4 on 2023-01-01 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0006_host_alter_task_options_alter_task_status_task_hosts'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ping.host')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='hosts',
            field=models.ManyToManyField(to='ping.hoststatus'),
        ),
    ]
